print("vamos a calular")
first_number=int(input("primer numero?"))
second_number=int(input("segundo numero"))
suma=(first_number+second_number)
resta=(first_number-second_number)
multiplicacion=(first_number*second_number)
division=(first_number/second_number)
print("suma", suma)
print("resta", resta)
print("multiplicacion",multiplicacion)
print("division",division)